// Code generated by goctl. DO NOT EDIT!
// Source: student.proto

package server

import (
	"context"

	"credit_certificate/student-rpc/internal/logic"
	"credit_certificate/student-rpc/internal/svc"
	"credit_certificate/student-rpc/pb"
)

type StudentcenterServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedStudentcenterServer
}

func NewStudentcenterServer(svcCtx *svc.ServiceContext) *StudentcenterServer {
	return &StudentcenterServer{
		svcCtx: svcCtx,
	}
}

func (s *StudentcenterServer) GetStudentInfo(ctx context.Context, in *pb.GetStudentInfoReq) (*pb.GetStudentInfoResp, error) {
	l := logic.NewGetStudentInfoLogic(ctx, s.svcCtx)
	return l.GetStudentInfo(in)
}
