// Code generated by goctl. DO NOT EDIT.
package types

type Course struct {
	Id         int64  `json:"id"`
	CourseName string `json:"CouerseName"`
	Teacher    string `json:"teacher"`
	BeginAt    string `json:"beginAt"`
	EndAt      string `json:"endAt"`
}

type CourseInfoReq struct {
	CourseId int64 `json:"courseId"`
}

type CourseInfoResp struct {
	CourseInfo Course `json:"courseInfo"`
}
