// Code generated by goctl. DO NOT EDIT!
// Source: teacher.proto

package server

import (
	"context"

	"credit_certificate/teacher-rpc/internal/logic"
	"credit_certificate/teacher-rpc/internal/svc"
	"credit_certificate/teacher-rpc/pb"
)

type TeachercenterServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedTeachercenterServer
}

func NewTeachercenterServer(svcCtx *svc.ServiceContext) *TeachercenterServer {
	return &TeachercenterServer{
		svcCtx: svcCtx,
	}
}

func (s *TeachercenterServer) GetTeacherInfo(ctx context.Context, in *pb.GetTeacherInfoReq) (*pb.GetTeacherInfoResp, error) {
	l := logic.NewGetTeacherInfoLogic(ctx, s.svcCtx)
	return l.GetTeacherInfo(in)
}
