// Code generated by goctl. DO NOT EDIT!
// Source: course.proto

package server

import (
	"context"

	"credit_certificate/course-rpc/internal/logic"
	"credit_certificate/course-rpc/internal/svc"
	"credit_certificate/course-rpc/pb"
)

type CoursecenterServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedCoursecenterServer
}

func NewCoursecenterServer(svcCtx *svc.ServiceContext) *CoursecenterServer {
	return &CoursecenterServer{
		svcCtx: svcCtx,
	}
}

func (s *CoursecenterServer) GetCourseInfo(ctx context.Context, in *pb.GetCourseInfoReq) (*pb.GetCourseInfoResp, error) {
	l := logic.NewGetCourseInfoLogic(ctx, s.svcCtx)
	return l.GetCourseInfo(in)
}
