// Code generated by goctl. DO NOT EDIT!
// Source: teacher.proto

package teachercenter

import (
	"context"

	"credit_certificate/teacher-rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	GetTeacherInfoReq  = pb.GetTeacherInfoReq
	GetTeacherInfoResp = pb.GetTeacherInfoResp
	Teacher            = pb.Teacher

	Teachercenter interface {
		GetTeacherInfo(ctx context.Context, in *GetTeacherInfoReq, opts ...grpc.CallOption) (*GetTeacherInfoResp, error)
	}

	defaultTeachercenter struct {
		cli zrpc.Client
	}
)

func NewTeachercenter(cli zrpc.Client) Teachercenter {
	return &defaultTeachercenter{
		cli: cli,
	}
}

func (m *defaultTeachercenter) GetTeacherInfo(ctx context.Context, in *GetTeacherInfoReq, opts ...grpc.CallOption) (*GetTeacherInfoResp, error) {
	client := pb.NewTeachercenterClient(m.cli.Conn())
	return client.GetTeacherInfo(ctx, in, opts...)
}
