// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.1
// source: student.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// StudentcenterClient is the client API for Studentcenter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StudentcenterClient interface {
	GetStudentInfo(ctx context.Context, in *GetStudentInfoReq, opts ...grpc.CallOption) (*GetStudentInfoResp, error)
}

type studentcenterClient struct {
	cc grpc.ClientConnInterface
}

func NewStudentcenterClient(cc grpc.ClientConnInterface) StudentcenterClient {
	return &studentcenterClient{cc}
}

func (c *studentcenterClient) GetStudentInfo(ctx context.Context, in *GetStudentInfoReq, opts ...grpc.CallOption) (*GetStudentInfoResp, error) {
	out := new(GetStudentInfoResp)
	err := c.cc.Invoke(ctx, "/pb.studentcenter/GetStudentInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StudentcenterServer is the server API for Studentcenter service.
// All implementations must embed UnimplementedStudentcenterServer
// for forward compatibility
type StudentcenterServer interface {
	GetStudentInfo(context.Context, *GetStudentInfoReq) (*GetStudentInfoResp, error)
	mustEmbedUnimplementedStudentcenterServer()
}

// UnimplementedStudentcenterServer must be embedded to have forward compatible implementations.
type UnimplementedStudentcenterServer struct {
}

func (UnimplementedStudentcenterServer) GetStudentInfo(context.Context, *GetStudentInfoReq) (*GetStudentInfoResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStudentInfo not implemented")
}
func (UnimplementedStudentcenterServer) mustEmbedUnimplementedStudentcenterServer() {}

// UnsafeStudentcenterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StudentcenterServer will
// result in compilation errors.
type UnsafeStudentcenterServer interface {
	mustEmbedUnimplementedStudentcenterServer()
}

func RegisterStudentcenterServer(s grpc.ServiceRegistrar, srv StudentcenterServer) {
	s.RegisterService(&Studentcenter_ServiceDesc, srv)
}

func _Studentcenter_GetStudentInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStudentInfoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StudentcenterServer).GetStudentInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.studentcenter/GetStudentInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StudentcenterServer).GetStudentInfo(ctx, req.(*GetStudentInfoReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Studentcenter_ServiceDesc is the grpc.ServiceDesc for Studentcenter service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Studentcenter_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.studentcenter",
	HandlerType: (*StudentcenterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetStudentInfo",
			Handler:    _Studentcenter_GetStudentInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "student.proto",
}
