// Code generated by goctl. DO NOT EDIT!
// Source: student.proto

package studentcenter

import (
	"context"

	"credit_certificate/student-rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	GetStudentInfoReq  = pb.GetStudentInfoReq
	GetStudentInfoResp = pb.GetStudentInfoResp
	Student            = pb.Student

	Studentcenter interface {
		GetStudentInfo(ctx context.Context, in *GetStudentInfoReq, opts ...grpc.CallOption) (*GetStudentInfoResp, error)
	}

	defaultStudentcenter struct {
		cli zrpc.Client
	}
)

func NewStudentcenter(cli zrpc.Client) Studentcenter {
	return &defaultStudentcenter{
		cli: cli,
	}
}

func (m *defaultStudentcenter) GetStudentInfo(ctx context.Context, in *GetStudentInfoReq, opts ...grpc.CallOption) (*GetStudentInfoResp, error) {
	client := pb.NewStudentcenterClient(m.cli.Conn())
	return client.GetStudentInfo(ctx, in, opts...)
}
